const initVal = {
  text: [],
  setText: () => {},
  isAddVocabDialog: false,
  setIsAddVocabDialog: () => {},
  isDeleteVocabDialog: false,
  setIsDeleteVocabDialog: () => {},
  mouseDownId: 0,
  setMouseDownId: () => {},
  mouseUpId: 0,
  setMouseUpId: () => {},
  selectedWords: "",
  setSelectedWords: () => {},
  vocab: [],
  setVocab: () => {},
  vocabId: 0,
  setVocabId: () => {},
  updateText: () => {},
  deletedVocab: { id: 0, word: "" },
  setDeletedVocab: () => {},
  handleAddVocabConfirmation: () => {},
  handleCancelAddVocab: () => {},
  addVocabRef: { current: null },
  deleteVocabRef: { current: null },
  openFileDialogRef: { current: null },
  handleMouseDown: () => {},
  handleMouseUp: () => {},
  handleIsDeleteVocabDialog: () => {},
  handleDeleteVocabConfirmation: () => {},
  handleIsAddVocabDialog: () => {},
  handleCancelDeleteVocab: () => {},
  handleInput: () => {},
  inputText: "",
  isSubmitted: false,
  handleSubmit: () => {},
  handleCancel: () => {},
  handleOpenFile: () => {},
  handleOpenDialog: () => {},
  createNew: false,
  setCreateNew: () => {},
  handleCreateNew: () => {},
  textAreaRef: { current: null },
  autoHeight: () => {},
  scrHeight: 56,
  textTitle: "",
  setTextTitle: () => {},
  handleTitleInput: () => {},
  saveData: () => {},
  printData: () => {},
  isNoTitle: false,
  isNoText: false,
};

export default initVal;
